id = "printf"
name = "Printf"
description = "Printf format string syntax highlighting for C, C++, Go, and other languages."
version = "0.2.0"
schema_version = 1
authors = ["ozacod"]
repository = "https://github.com/ozacod/zed-printf"

[grammars.printf]
repository = "https://github.com/ozacod/tree-sitter-printf"
commit = "b474fff98d991f3079fb09b7701032344167f848"
