id = "printf"
name = "Printf"
description = "Printf format string syntax highlighting for C, C++, Go, and other languages."
version = "0.1.0"
schema_version = 1
authors = ["ozacod"]
repository = "https://github.com/ozacod/zed-printf"

[grammars.printf]
repository = "https://github.com/pstuifzand/tree-sitter-printf"
commit = "425c915e7eca0706202df5c569a2d5ae3cb3670a"
