id = "printf"
name = "Printf"
description = "Printf format string syntax highlighting for C, C++, Go, and other languages."
version = "0.1.0"
schema_version = 1
authors = ["ozacod"]
repository = "https://github.com/ozacod/zed-printf"

[grammars.printf]
repository = "https://github.com/ozacod/tree-sitter-printf"
commit = "89110625333e3658d24c23ac8dc7309578f44613"
